// Generated by CoffeeScript 1.3.3
(function() {

  ({
    box2d: (typeof exports !== "undefined" && exports !== null) && exports || this.box2d || (this.box2d = {})
  });

  box2d.Bound = (function() {

    function Bound() {
      this.value = 0;
      this.proxyId = 0;
      this.stabbingCount = 0;
    }

    Bound.prototype.IsValid = function() {
      return (this.value != null) && isFinite(this.value) && (this.proxyId != null) && isFinite(this.proxyId) && (this.stabbingCount != null) && isFinite(this.stabbingCount);
    };

    Bound.prototype.IsLower = function() {
      return (this.value & 0x01) === 0;
    };

    Bound.prototype.IsUpper = function() {
      return (this.value & 0x01) === 1;
    };

    Bound.prototype.Swap = function(bound) {
      var tmpProxyId, tmpStabbingCount, tmpValue;
      if (!((bound.value != null) && (bound.proxyId != null) && (bound.stabbingCount != null))) {
        throw new TypeError;
      }
      tmpValue = this.value;
      tmpProxyId = this.proxyId;
      tmpStabbingCount = this.stabbingCount;
      this.value = bound.value;
      this.proxyId = bound.proxyId;
      this.stabbingCount = bound.stabbingCount;
      bound.value = tmpValue;
      bound.proxyId = tmpProxyId;
      bound.stabbingCount = tmpStabbingCount;
    };

    return Bound;

  })();

}).call(this);
