// Generated by CoffeeScript 1.3.3
(function() {

  ({
    box2d: (typeof exports !== "undefined" && exports !== null) && exports || this.box2d || (this.box2d = {})
  });

  box2d.BufferedPair = (function() {

    function BufferedPair() {
      this.proxyId1 = 0;
      this.proxyId2 = 0;
    }

    return BufferedPair;

  })();

}).call(this);
