// Generated by CoffeeScript 1.3.3
(function() {

  ({
    box2d: (typeof exports !== "undefined" && exports !== null) && exports || this.box2d || (this.box2d = {})
  });

  box2d.Pair = (function() {

    function Pair() {
      this.nullPair = box2d.Settings.USHRT_MAX;
      this.nullProxy = box2d.Settings.USHRT_MAX;
      this.tableCapacity = box2d.Settings.maxPairs;
      this.tableMask = this.tableCapacity - 1;
      this.pairBuffered = 0x0001;
      this.pairRemoved = 0x0002;
      this.pairFinal = 0x0004;
      this.userData = null;
      this.proxyId1 = 0;
      this.proxyId2 = 0;
      this.next = 0;
      this.status = 0;
    }

    Pair.prototype.SetBuffered = function() {
      this.status |= this.pairBuffered;
      return this;
    };

    Pair.prototype.ClearBuffered = function() {
      this.status &= ~this.pairBuffered;
      return this;
    };

    Pair.prototype.IsBuffered = function() {
      return (this.status & this.pairBuffered) === this.pairBuffered;
    };

    Pair.prototype.SetRemoved = function() {
      this.status |= this.pairRemoved;
      return this;
    };

    Pair.prototype.ClearRemoved = function() {
      this.status &= ~this.pairRemoved;
      return this;
    };

    Pair.prototype.IsRemoved = function() {
      return (this.status & this.pairRemoved) === this.pairRemoved;
    };

    Pair.prototype.SetFinal = function() {
      this.status |= this.pairFinal;
      return this;
    };

    Pair.prototype.IsFinal = function() {
      return (this.status & this.pairFinal) === this.pairFinal;
    };

    return Pair;

  })();

}).call(this);
