// Generated by CoffeeScript 1.3.3
(function() {

  ({
    box2d: (typeof exports !== "undefined" && exports !== null) && exports || this.box2d || (this.box2d = {})
  });

  describe('AABB', function() {
    var aabb, another_vector2d, vector2d;
    vector2d = null;
    another_vector2d = null;
    aabb = null;
    beforeEach(function() {
      vector2d = new box2d.Vector2D(2, 3);
      another_vector2d = new box2d.Vector2D(4, 5);
      aabb = new box2d.AABB(vector2d, another_vector2d);
    });
    it('can be initialized', function() {
      expect(aabb.minVertex.x).toBe(2);
      expect(aabb.minVertex.y).toBe(3);
      expect(aabb.maxVertex.x).toBe(4);
      return expect(aabb.maxVertex.y).toBe(5);
    });
    return it('can be validated', function() {
      var valid_aabb;
      valid_aabb = aabb.IsValid();
      return expect(valid_aabb).toBe(true);
    });
  });

}).call(this);
