// Generated by CoffeeScript 1.3.3
(function() {

  ({
    box2d: (typeof exports !== "undefined" && exports !== null) && exports || this.box2d || (this.box2d = {})
  });

  describe('Math', function() {
    var matrix2x2, scalar, vector2d;
    scalar = null;
    vector2d = null;
    matrix2x2 = null;
    beforeEach(function() {
      scalar = 4;
      vector2d = new box2d.Vector2D(2, 3);
      matrix2x2 = new box2d.Matrix2x2(new box2d.Vector2D(1, 2), new box2d.Vector2D(3, 4));
    });
    return it('can validate', function() {
      return expect(box2d.Math.IsValid(scalar)).toBe(true);
    });
  });

}).call(this);
