// Generated by CoffeeScript 1.3.3
(function() {

  ({
    box2d: (typeof exports !== "undefined" && exports !== null) && exports || this.box2d || (this.box2d = {})
  });

  box2d.Settings = (function() {

    function Settings() {}

    Settings.USHRT_MAX = 0x0000ffff;

    Settings.pi = Math.PI;

    Settings.massUnitsPerKilogram = 1.0;

    Settings.timeUnitsPerSecond = 1.0;

    Settings.lengthUnitsPerMeter = 30.0;

    Settings.maxManifoldPoints = 2;

    Settings.maxShapesPerBody = 64;

    Settings.maxPolyVertices = 8;

    Settings.maxProxies = 1024;

    Settings.maxPairs = 8 * Settings.maxProxies;

    Settings.linearSlop = 0.005 * Settings.lengthUnitsPerMeter;

    Settings.angularSlop = 2.0 / 180.0 * Settings.pi;

    Settings.velocityThreshold = 1.0 * Settings.lengthUnitsPerMeter / Settings.timeUnitsPerSecond;

    Settings.maxLinearCorrection = 0.2 * Settings.lengthUnitsPerMeter;

    Settings.maxAngularCorrection = 8.0 / 180.0 * Settings.pi;

    Settings.contactBaumgarte = 0.2;

    Settings.timeToSleep = 0.5 * Settings.timeUnitsPerSecond;

    Settings.linearSleepTolerance = 0.01 * Settings.lengthUnitsPerMeter / Settings.timeUnitsPerSecond;

    Settings.angularSleepTolerance = 2.0 / 180.0 / Settings.timeUnitsPerSecond;

    Settings.Assert = function(a) {
      var nullVec;
      nullVec = {
        x: 0
      };
      if (!a) {
        nullVec.x++;
        return false;
      }
      return true;
    };

    return Settings;

  })();

}).call(this);
