// Generated by CoffeeScript 1.3.3
(function() {

  ({
    box2d: (typeof exports !== "undefined" && exports !== null) && exports || (this.box2d = {})
  });

  box2d.Vec2 = (function() {

    function Vec2(x, y) {
      this.x = x != null ? x : 0.0;
      this.y = y != null ? y : 0.0;
    }

    Vec2.prototype.SetZero = function() {
      this.x = 0.0;
      this.y = 0.0;
    };

    Vec2.prototype.Set = function(x, y) {
      this.x = x;
      this.y = y;
    };

    Vec2.prototype.SetV = function(v) {
      this.x = v.x;
      this.y = v.y;
    };

    Vec2.prototype.Negative = function() {
      return new box2d.Vec2(-this.x, -this.y);
    };

    Vec2.prototype.Copy = function() {
      return new box2d.Vec2(this.x, this.y);
    };

    Vec2.prototype.Add = function(v) {
      this.x += v.x;
      this.y += v.y;
    };

    Vec2.prototype.Subtract = function(v) {
      this.x -= v.x;
      this.y -= v.y;
    };

    Vec2.prototype.Multiply = function(a) {
      this.x *= a;
      this.y *= a;
    };

    return Vec2;

  })();

}).call(this);
