// Generated by CoffeeScript 1.3.3
(function() {

  ({
    box2d: (typeof exports !== "undefined" && exports !== null) && exports || this.box2d || (this.box2d = {})
  });

  describe('BoundValues', function() {
    var bound_values;
    bound_values = null;
    beforeEach(function() {
      return bound_values = new box2d.BoundValues();
    });
    it('can be initialized', function() {
      expect(bound_values.lowerValues[0]).toBe(0);
      expect(bound_values.lowerValues[1]).toBe(0);
      expect(bound_values.upperValues[0]).toBe(0);
      return expect(bound_values.upperValues[1]).toBe(0);
    });
    return it('can be validated', function() {
      return expect(bound_values.IsValid()).toBe(true);
    });
  });

}).call(this);
