// Generated by CoffeeScript 1.3.3
(function() {

  ({
    box2d: (typeof exports !== "undefined" && exports !== null) && exports || this.box2d || (this.box2d = {})
  });

  describe('BufferedPair', function() {
    var buffered_pair;
    buffered_pair = null;
    beforeEach(function() {
      return buffered_pair = new box2d.BufferedPair();
    });
    return it('can be initialized', function() {
      expect(buffered_pair.proxyId1).toBe(0);
      return expect(buffered_pair.proxyId2).toBe(0);
    });
  });

}).call(this);
