// Generated by CoffeeScript 1.3.3
(function() {

  ({
    box2d: (typeof exports !== "undefined" && exports !== null) && exports || this.box2d || (this.box2d = {})
  });

  describe('PairManager', function() {
    var pair_manager;
    pair_manager = null;
    beforeEach(function() {
      return pair_manager = new box2d.PairManager();
    });
    return it('can be initialized', function() {
      var broadPhase, callback, pair_manager_with_parameters;
      broadPhase = new Object();
      callback = function() {};
      pair_manager_with_parameters = new box2d.PairManager(broadPhase, callback);
      expect(typeof pair_manager_with_parameters.broadPhase).toBe('object');
      expect(typeof pair_manager_with_parameters.callback).toBe('function');
      expect(pair_manager_with_parameters.pairs).toBe(null);
      expect(pair_manager_with_parameters.freePair).toBe(0);
      expect(pair_manager_with_parameters.pairCount).toBe(0);
      expect(pair_manager_with_parameters.pairBuffer).toBe(null);
      expect(pair_manager_with_parameters.pairBufferCount).toBe(0);
      expect(pair_manager_with_parameters.hashTable).toBe(null);
      expect(pair_manager.broadPhase).toBe(null);
      expect(pair_manager.callback).toBe(null);
      expect(pair_manager.pairs.length).toBe(box2d.Settings.maxPairs);
      expect(pair_manager.freePair).toBe(0);
      expect(pair_manager.pairCount).toBe(0);
      expect(pair_manager.pairBuffer.length).toBe(box2d.Settings.maxPairs);
      expect(pair_manager.pairBufferCount).toBe(0);
      return expect(pair_manager.hashTable.length).toBe(box2d.Settings.maxPairs);
    });
  });

}).call(this);
